/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type CreateRowDto = {
    /**
     * Data content
     */
    data: any;
    /**
     * function id
     */
    modelId: string;
    /**
     * Custom row id, automatically generated by default. Only a maximum of 32 bits is allowed.
     */
    rowId?: string;
};
