/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type DeleteDepartmentReqDto = {
    /**
     * Organization Code (organizationCode)
     */
    organizationCode: string;
    /**
     * Department system ID (automatically generated by the Authing system and cannot be modified)
     */
    departmentId: string;
    /**
     * The type of department ID used in this call
     */
    departmentIdType?: DeleteDepartmentReqDto.departmentIdType;
    /**
     * Tenant ID
     */
    tenantId?: string;
};

export namespace DeleteDepartmentReqDto {

    /**
     * The type of department ID used in this call
     */
    export enum departmentIdType {
        DEPARTMENT_ID = 'department_id',
        OPEN_DEPARTMENT_ID = 'open_department_id',
        SYNC_RELATION = 'sync_relation',
        CUSTOM_FIELD = 'custom_field',
        CODE = 'code',
    }


}
