/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { DepartmentI18nDto } from './DepartmentI18nDto';

export type InvitationDepartmentRespDto = {
    /**
     * Organization Code (organizationCode)
     */
    organizationCode: string;
    /**
     * Department system ID (automatically generated by the Authing system and cannot be modified)
     */
    departmentId: string;
    /**
     * Department creation time
     */
    createdAt: string;
    /**
     * Modification time
     */
    updatedAt?: string;
    /**
     * Custom department ID, used to store customized IDs
     */
    openDepartmentId?: string;
    /**
     *Department name
     */
    name: string;
    /**
     * Department head ID
     */
    leaderUserIds?: Array<string>;
    /**
     * Department description
     */
    description?: string;
    /**
     * Parent department id, if it is the root department, pass root
     */
    parentDepartmentId: string;
    /**
     * Department identification code
     */
    code?: string;
    /**
     * Parent department code
     */
    parentDepartmentCode: string;
    /**
     * Number of people in the department (only including direct members)
     */
    membersCount: number;
    /**
     * Whether to include sub-departments
     */
    hasChildren: boolean;
    /**
     * Whether it is a virtual department
     */
    isVirtualNode?: boolean;
    /**
     *Multi-language settings
     */
    i18n?: DepartmentI18nDto;
    /**
     * Extended field data of department
     */
    customData?: any;
    /**
     *Positions related to departments
     */
    posts?: Array<string>;
    /**
     * Position id list
     */
    postIdList?: Array<string>;
    /**
     * Department status
     */
    status?: boolean;
    /**
     * Access restrictions
     */
    allow?: string;
    /**
     *Department ID
     */
    id: string;
    /**
     * ID path from top-level department to current department
     */
    idPath?: Array<string>;
    /**
     * Department name path from top-level department to current department
     */
    namePath?: Array<string>;
    /**
     * Department code path from top-level department to current department
     */
    codePath?: (string | null);
};
